language: 
  - node_js
  - python
node_js:
  - "10.16.0"
python:
  - "3.6"
cache: 
  - yarn
  - pip
sudo: true
before_script:
  export TZ=Australia/Perth

jobs:
  allow_failures:
   - script: python3 Scripts/lint.py
  include:
    - stage: Install
      script: yarn
    - stage: Lint
      script: python3 Scripts/lint.py
    - stage: Build
      script: node node_modules/electron-builder/out/cli/cli.js . -l AppImage --publish never

# We will need to create a more consistent branch structure before publishing to Bintray