language: node_js
node_js:
  - "10.16.0"
cache: npm
sudo: true
jobs:
  allow_failures:
   - script: eslint -c .eslintrc.json App/JS/client.js
  include:
    - stage: Lint
      script: sudo npm install -g eslint eslint-config-google
      script: eslint -c .eslintrc.json App/JS/client.js
    - stage: Install
      script: echo "Installing dependencies"
      script: npm install
      script: npm install --save-dev electron-packager
      script: npm install --save-dev electron-installer-debian
    - stage: Build
      script: echo "Building for all available platforms..."
      script: node ./node_modules/electron-packager/bin/electron-packager.js . RoboHUD --platform=linux --arch=x64 --icon=Assets/icon.png --out=Builds
      script: electron-installer-debian --src Builds/RoboHUD-linux-x64 --dest Build/installers/ --arch amd64
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases..."
      deploy:
        provider: releases
        api_key: $personal_access_token
        skip_cleanup: true
        file:
          - Build/installers/*
        draft: true
