language: node_js
node_js:
  - "10.16.0"
cache: npm
sudo: true
jobs:
  allow_failures:
   - script: eslint -c .eslintrc.json App/JS/client.js
  include:
    - stage: Lint
      script: sudo npm install -g eslint eslint-config-google
      script: eslint -c .eslintrc.json App/JS/client.js
    - stage: Build & release
      script: echo "Installing dependencies"
      script: npm install
      script: npm install --save-dev electron-packager
      script: echo "Building for all available platforms..."
      script: node ./node_modules/electron-packager/bin/electron-packager.js . RoboHUD --platform=linux --arch=x64 --icon=Assets/icon.png --out=Builds && zip Builds/Linux-x64.zip Builds/RoboHUD-linux-x64 -r
      deploy:
        provider: releases
        api_key: $personal_access_token
        skip_cleanup: true
        file:
          - Builds/Linux-x64.zip
        name: Automatic Travis build on $(date + '%d/%m/%y at %R')
        draft: true
